### PR TITLE
Add support for template id, tags and params

### PR DESCRIPTION
**Pull request by boryn**
Hi! I have extended the library so that it can be used to send emails using SendinBlue templates with support for params and tags. There is an example of usage in the README

### CODE REVIEW

**Comment by boryn** [comment]
PS. Please make a `v2` branch at the level of `2.0.3` tag so that I can make a pull request as well for the version 2 (it's not possible to make a pull request against a tag).

**Comment by Biptaste** [comment]
Hi, I tested your PR but it doesn't work, I had this error `Call to undefined method App\Mail\TemplateTest::sendinblue()`
It seems normal because your sendinblue method is in the class SendinBlueTransport and my class TemplateTest extends of Mailable which are not related.
What version of Laravel are you using ?

**Comment by boryn** [comment]
Actually I was developing this in the v2 version with Laravel 6 and was working properly. Maybe it would need some further adjustments to the v3?

BTW. Did you use `use SendinBlue;`?

**Comment by boryn** [comment]
@Biptaste this is my full example of class extending Mailable. It's imporant to read in the trait `SendinBlue` which is in `src/SendinBlue.php`: 

```php
<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Webup\LaravelSendinBlue\SendinBlue; // <---
use Webup\LaravelSendinBlue\SendinBlueTransport;

class Offer extends Mailable implements ShouldQueue
{
    use Queueable;
    use SendinBlue; // <---
    use SerializesModels;

    public function build()
    {
        return $this
            ->view([])
            ->subject(SendinBlueTransport::USE_TEMPLATE_SUBJECT)
            ->sendinblue(
                [
                    'template_id' => 84,
                    'tags'        => ['offer'],
                    'params'      => [
                        'NAME'   => 'John',
                        'LINK'   => 'https://www.example.com',
                        'AMOUNT' => '29',
                    ],
                ]
            );
    }
}
```

**Comment by Biptaste** [comment]
@boryn Thank you, I released it in v2.1.0 and v3.3.0

**Comment by boryn** [comment]
@Biptaste I wonder why Github shows the last release as one from 2018??

image

**Pull request merged**
